### ISSUE TITLE
kliko-run error: urllib3 connection error due to version python-urllib3 (v.1.7.1) vs. pip urllib3 (v1.16)

### ISSUE THREAD

**Issue by JulienNGirard** [gijzelaerr/kliko#12]
#### ubuntu deb python-urllib3 v.1.7.1 of 14.04 LTS won't work with kliko (not used in a virtualenv):

(this package is installed along with python-pip using apt-get)
when using kliko-run image, I get this error:

> urllib3.connection.match_hostname = match_hostname
> AttributeError: 'module' object has no attribute 'connection'

When I import urllib3 in python: 

> In [2]: urllib3.**file**
> Out[2]: '/usr/lib/python2.7/dist-packages/urllib3/**init**.pyc'
> 
> In [3]: urllib3.**version**
> Out[3]: '1.7.1'

does not have urllib3.connection
#### whereas the pip package of urllib3 (v. 1.16) has the correct module:

> In [1]: import urllib3
> 
> In [2]: urllib3.**file**
> Out[2]: '/usr/local/lib/python2.7/dist-packages/urllib3/**init**.pyc'
> 
> In [3]: urllib3.**version**
> Out[3]: '1.16'
> 
> In [4]: urllib3.
> 
> urllib3.HTTPConnectionPool
> urllib3.connection
> urllib3.logging
> urllib3.HTTPResponse
> urllib3.connection_from_url
> urllib3.make_headers
> urllib3.HTTPSConnectionPool
> urllib3.connectionpool
> urllib3.packages

**Comment by gijzelaerr** [comment]
This is actually quite a mess. I think for now we just have to say to use `docker-py` in a virtualenv or don't install it system wide on Ubuntu 14.04. I'm going to switch all the radioastro packages to Ubuntu 16.04 soon also.

Original issue here:
https://github.com/docker/docker-py/issues/1054

**Comment by gijzelaerr** [comment]
this fixes the problem for me, can you verify @JulienNGirard : `pip install urllib3[secure]`

**Comment by JulienNGirard** [comment]
ok it seems to behave. I removed everything related to urllib3 on my system and installed urllib3[secure].
