### ISSUE TITLE
Docker run: parameters.json is mounted as a directory when a relative path is given

### ISSUE THREAD

**Issue by JulienNGirard** [gijzelaerr/kliko#13]
Related to [this issue](http://stackoverflow.com/questions/34134343/single-file-volume-mounted-as-directory-in-docker)

When this command is issued on the test example:
`docker run -it -v parameters.json:/parameters.json:ro -v input:/input:ro -v output:/output:rw radioastro/klikotest bash`

(btw, there is a typo in the readthedocs in introduction.rst   (( ".join" --> ".json" )) )

result:  parameters.json is mounted as a directory

> root@eeb365d00398:/# ls -la parameters.json
> total 8
> drwxr-xr-x  2 root root 4096 Jun 30 13:57 .
> drwxr-xr-x 58 root root 4096 Jun 30 15:46 ..

but with the absolute path to parameters.json specified:
`docker run -it -v /home/user/kliko/kliko/examples/parameters.json:/parameters.json:ro -v input:/input:ro -v output:/output:rw radioastro/klikotest bash`

result: parameters.json is correctly mounted as a file

> root@2b9030faa09f:/# ls -la parameters.json 
> -rw-rw-r-- 1 1000 1000 81 Jun 28 13:26 parameters.json

**Comment by gijzelaerr** [comment]
yeah i forgot to mention this to you, this is one of the other things docker sucks and keeps on sucking.

you can also  use `-v`pwd`parameters.json:/parameters.json`

This is not really an issue with kliko, or is this wronly in the documentation somewhere?

**Comment by JulienNGirard** [comment]
Thanks, yes, this is more a docker related thing, but users of kliko might have this error anyway based on the readthedocs documentation.

you mean `-v $(pwd)parameters.json:/parameters.json` I suppose.

You have to amend the "Running a kliko container" section in https://github.com/gijzelaerr/kliko/blob/master/doc/introduction.rst
where the command is :
`$ docker run -v parameters.json:/parameters.join:ro -v input:/input:ro -v output:/output:rw <image-name> kliko`
- has local paths to files
- has a typo at "parameters.join"

My small example is working smoothly now. I look forward to test with the form, once it's added on RODRIGUES.

**Comment by JulienNGirard** [comment]
and when using 
`docker run .......   <image-name> kliko`  
it generates an error

> docker: Error response from daemon: Container command 'kliko' not found or does not exist..

whereas 
`docker run .......   <image-name> ./kliko`  
works.

the "kliko" python executable (that is added in the DockerFile) is not know as a system command.

**Comment by gijzelaerr** [comment]
is this in the docs? Otherwise, kliko is just not in the PATH so you need to specify the path manually. Do you think it would be more clear if you don't need to do that? i'm not sure if it is a good idea to add `/` to the system PATH.

**Comment by gijzelaerr** [comment]
fixed https://github.com/gijzelaerr/kliko/commit/cae144e37084805798e4330931e308c9977c34ca
