### ISSUE TITLE
How does kliko compare to CWL?

### ISSUE THREAD

**Issue by tetron** [gijzelaerr/kliko#15]
Are you familiar with the Common Workflow Language effort?  http://commonwl.org?  It is a spec for wrapping scientific tools inside Docker containers and connecting them into workflows. The 1.0 spec was recently released and there are several several projects and vendors committed to implementing it.

**Comment by gijzelaerr** [comment]
Thanks for pointing this out, I was not aware of this project. I will check it out, if it does what we need and has a large community then we don't need kliko.

**Comment by tetron** [comment]
I suspect it does do most of what you need, and if there are oversights we would like to hear about them so they can be addressed.  The main cultural difference is that CWL is emerging from the bioinformatics community, while there is nothing about the technology that is biology specific, we don't yet have any users from the physics/astronomy community.

**Comment by gijzelaerr** [comment]
Yes, it does a lot of what we try to do plus a lot more. I should have known about this project before,  I've put quite a lot of time and effort in polishing Kliko :) I'm going to try to work with CWL and see if it works for us.

**Comment by gijzelaerr** [comment]
I guess we took the decision to base all our work on CWL. Thanks for pointing this out :)
